#### DoD Vanilla Changes ####
#Greyling
Greyling:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Boar
Boar:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Neck
Neck:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf
Greydwarf:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf Shaman
Greydwarf Shaman:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Greydwarf Brute
Greydwarf Brute:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
#Skeleton
Skeleton:
  size: 0.02
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Fuling
Fuling:
  size: 0.02
  Meadows:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
      
## Forest Wolf
Forest Wolf:
  size: 0.02
  Meadows:
    health:
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    damage: 
        0: 1
        1: 1.1
        2: 1.2
        3: 1.3
        4: 1.4
        5: 1.5
    damage taken: 
        0: 1
        1: 0.95
        2: 0.9
        3: 0.85
        4: 0.8
        5: 0.75
    attack speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25
    movement speed: 
        0: 1
        1: 1.05
        2: 1.1
        3: 1.15
        4: 1.2
        5: 1.25          
## Molluscan
Molluscan:
  size: 0.02
  infusion: 
      Fire: 0
      Frost: 9
      Lightning: 0
      Spirit: 9
      Poison: 9
      Chaos: 9
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25         
## Thief
Herfiligr:
  size: 0
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 0
      Spirit: 12
      Poison: 12
      Chaos: 12
  Meadows:
    nokey_defeated_eikthyr:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_eikthyr:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
  Black Forest:
      health:
          0: 3
          1: 3.05
          2: 3.1
          3: 3.15
          4: 3.2
          5: 3.25
      damage: 
          0: 3
          1: 3.1
          2: 3.2
          3: 3.3
          4: 3.4
          5: 3.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
  Swamp:
      health:
          0: 6
          1: 6.05
          2: 6.1
          3: 6.15
          4: 6.2
          5: 6.25
      damage: 
          0: 6
          1: 6.1
          2: 6.2
          3: 6.3
          4: 6.4
          5: 6.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
  Mountain:
      health:
          0: 10
          1: 10.05
          2: 10.1
          3: 10.15
          4: 10.2
          5: 10.25
      damage: 
          0: 10
          1: 10.1
          2: 10.2
          3: 10.3
          4: 10.4
          5: 10.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
  Plains:
      health:
          0: 14
          1: 14.05
          2: 14.1
          3: 14.15
          4: 14.2
          5: 14.25
      damage: 
          0: 13
          1: 13.1
          2: 13.2
          3: 13.3
          4: 13.4
          5: 13.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
  Mistlands:
      health:
          0: 17
          1: 17.05
          2: 17.1
          3: 17.15
          4: 17.2
          5: 17.25
      damage: 
          0: 17
          1: 17.1
          2: 17.2
          3: 17.3
          4: 17.4
          5: 17.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25