#### DoD Vanilla Changes ####
#Skeleton
Skeleton:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
#Rancid Remains
Rancid Remains:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Blob
Blob:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Oozer
Oozer:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Draugr
Draugr:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Draugr Elite
Draugr Elite:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Wraith
Wraith:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Leech
Leech:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Surtling
Surtling:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
# Scoundrel
Scoundrel:
  size: 0
  infusion: 
      Fire: 0
      Frost: 0
      Lightning: 0
      Spirit: 12
      Poison: 12
      Chaos: 12
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25       
# Slimy Wendigo
Slimy Wendigo:
  size: 0.02
  Swamp:
    nokey_defeated_bonemass:
      health:
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      damage: 
          0: 1
          1: 1.1
          2: 1.2
          3: 1.3
          4: 1.4
          5: 1.5
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
    key_defeated_bonemass:
      health:
          0: 1.5
          1: 1.55
          2: 1.6
          3: 1.65
          4: 1.7
          5: 1.75
      damage: 
          0: 1.5
          1: 1.6
          2: 1.7
          3: 1.8
          4: 1.9
          5: 2
      damage taken: 
          0: 1
          1: 0.95
          2: 0.9
          3: 0.85
          4: 0.8
          5: 0.75
      attack speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25
      movement speed: 
          0: 1
          1: 1.05
          2: 1.1
          3: 1.15
          4: 1.2
          5: 1.25       
        